### ISSUE TITLE
TypeError: '_io.TextIOWrapper'

### ISSUE THREAD

**Issue by kosty4** [SaschaStenger/FakeNewsNet_modified#6]
the regular repo runs fine, but i get this error when trying.
Thanks.
`Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from tweet_collection import TweetCollector
  File "/home/user/FakeNewsNetMod/code/tweet_collection.py", line 12, in <module>
    line_1 = fKeysIn[0].rstrip().split(',')
TypeError: '_io.TextIOWrapper' object is not subscriptable
`

**Comment by SaschaStenger** [comment]
Oh, yeah this is one of the parts, that i changed from my version, as i had the keys for my `twarc` instance just hardcoded into the class. I took the code, that read the keys out of the key-file. 
I'll fix it. 
In the meantime, if you want to run the code without waiting for my fix, just go into the  `tweet_collection.py`

delete this block

```
with open("resources/tweet_keys_file.txt", 'r') as fKeysIn:
    next(fKeysIn)
    line_1 = fKeysIn[0].rstrip().split(',')
```

and just paste in your four keys into this line
`t = Twarc(line_1[0], line_1[1], line_1[2], line_1[3])`

so that it says:
`t = Twarc('xxx', 'xxx', 'xxx', 'xxx')`

This should work, as twarc is only using a single key.

**Comment by SaschaStenger** [comment]
Pushed the fix. 
And i tested it as well, this time. Should run.
